name: Release package

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      release:
        description: 'The type of release: major, minor, or patch'
        options:
          -
          - patch
          - prerelease
          - minor
          - major
        required: true
        type: choice

jobs:
  version-and-tag:
    uses: ./.github/workflows/version-tag.yml
    with:
      release: ${{ inputs.release }}

  publish:
    uses: ./.github/workflows/publish-package.yml
    with:
      jsr: true
      npm: true

  github-pages:
    uses: ./.github/workflows/nextjs.yml
