name: Test

on:
  push:
    branches:
      - main

env:
  ACTIONS_RUNNER_DEBUG: true

jobs:
   generate-badges:
     runs-on: ubuntu-latest
     steps:
         - name: Checkout
           uses: actions/checkout@v4

         - name: Setup Node
           uses: actions/setup-node@v4
           with:
             node-version: "lts/*"
             cache: npm

         - name: Restore cache node_modules
           uses: actions/cache@v4
           with:
             path: |
               ~/.npm
             key: ${{ runner.os }}-versioning-${{ hashFiles('**/package-lock.json') }}
             restore-keys: |
               ${{ runner.os }}-versioning-

         - name: Restore cache test-cache
           uses: actions/cache@v4
           with:
             path: |
               ${{ github.workspace }}/.jest-cache
             key: ${{ runner.os }}-test-${{ hashFiles('{src,__tests__}/**/*.{ts,tsx}') }}-${{ hashFiles('**/package-lock.json') }}
             restore-keys: |
               ${{ runner.os }}-test-

         - name: Install dependencies
           run: npm install

         - name: Test coverage
           run: |
             npm run test:coverage

         - name: Generating coverage badges
           uses: jpb06/coverage-badges-action@latest
           with:
             branches: main
             badges-icon: jest
             output-folder: ./site/public/badges
